nodeLinker: node-modules

httpProxy: "http://proxy.canon.co.jp:10080"
httpsProxy: "http://proxy.canon.co.jp:10080"
npmRegistryServer: "http://itg-srv.cgn.canon.co.jp:4873"
npmPublishRegistry: "http://itg-srv.cgn.canon.co.jp:4873"
npmAuthToken: "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"
unsafeHttpWhitelist: "itg-srv.cgn.canon.co.jp"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
