version: '2.4'

x-env: &env
  SERVER_PORT: &SERVER_PORT ${SERVER_PORT:?}
  STORYBOOK_PORT: &STORYBOOK_PORT ${STORYBOOK_PORT:?}
  # internal
  DATABASE_URL: postgres://app:app@db/app


x-app: &app
  image: "csea-dev"
  build:
    context: .
    args:
      - http_proxy
      - https_proxy
  volumes:
    - .:/app

services:
  app:
    <<: *app
    environment:
      <<: *env

  storybook:
    <<: *app
    command: yarn web storybook -p ${STORYBOOK_PORT}
    ports:
      - "$STORYBOOK_PORT:$STORYBOOK_PORT"

  server:
    <<: *app
    command: yarn workspace @csea/cli cli start
    ports:
      - "${SERVER_PORT}:80"
    environment:
      <<: *env

  db:
    image: "timescale/timescaledb:latest-pg13"
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
