version: '2.4'

x-env: &env
  SERVER_PORT: &SERVER_PORT ${SERVER_PORT:?}
  ORACLE_USER: &ORACLE_USER ${ORACLE_USER}
  ORACLE_PASSWORD: &ORACLE_PASSWORD ${ORACLE_PASSWORD}
  ORACLE_CONFIG: &ORACLE_CONFIG ${ORACLE_CONFIG}
  LDAP_URL: &LDAP_URL ${LDAP_URL}
  # internal
  DATABASE_URL: postgres://app:app@db/app


x-app: &app
  image: "csea-dev"
  build:
    context: .
    args:
      - http_proxy
      - https_proxy
  volumes:
    - .:/app
  environment:
    - DATABASE_URL=postgres://app:app@db/app

services:
  app:
    <<: *app
    environment:
      <<: *env

  server:
    <<: *app
    command: bash -c 'wait-for-it db:5432 -- yarn db-migrate up && csea server start'
    ports:
      - "${SERVER_PORT}:80"
    environment:
      <<: *env
    depends_on:
      - "db"

  db:
    image: "postgres:14"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
