version: '2.4'

x-env: &env
  SERVER_PORT: &SERVER_PORT ${SERVER_PORT:?}
  STORYBOOK_PORT: &STORYBOOK_PORT ${STORYBOOK_PORT:?}
  # optional
  ORACLE_USER: &ORACLE_USER ${ORACLE_USER}
  ORACLE_PASSWORD: &ORACLE_PASSWORD ${ORACLE_PASSWORD}
  ORACLE_CONFIG: &ORACLE_CONFIG ${ORACLE_CONFIG}
  LDAP_URL: &LDAP_URL ${LDAP_URL}
  # internal
  DATABASE_URL: postgres://app:app@db/app


x-app: &app
  image: "csea-dev"
  build:
    context: .
    args:
      - http_proxy
      - https_proxy
  volumes:
    - .:/app
  environment:
    - DATABASE_URL=postgres://app:app@db/app

services:
  app:
    <<: *app
    environment:
      <<: *env

  storybook:
    <<: *app
    command: yarn web storybook -p ${STORYBOOK_PORT}
    ports:
      - "$STORYBOOK_PORT:$STORYBOOK_PORT"

  server:
    <<: *app
    command: bash -c 'yarn db-migrate up && yarn workspace @csea/cli nodemon --exec "yarn cli start"'
    ports:
      - "${SERVER_PORT}:80"
    environment:
      <<: *env

  db:
    image: "postgres:14"
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
