version: '2.4'

x-env: &env
  SERVER_PORT: &SERVER_PORT ${SERVER_PORT:?}
  # internal
  DATABASE_URL: postgres://app:app@db/app


x-app: &app
  image: "csea-dev"
  build:
    context: .
    args:
      - http_proxy
      - https_proxy
  volumes:
    - .:/app
  environment:
    - DATABASE_URL=postgres://app:app@db/app

services:
  server:
    <<: *app
    command: bash -c 'wait-for-it db:5432 -- yarn db-migrate up && csea start'
    ports:
      - "${SERVER_PORT}:80"
    environment:
      <<: *env

  db:
    image: "postgres:14"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
