export enum ErrorKind {
  SystemNotFound = "SystemNotFound",
  SystemAlreadyExist = "SystemAlreadyExist",
  RoleNotFound = "RoleNotFound",
  RoleAlreadyExist = "RoleAlreadyExist",
  RoleUserNotFound = "RoleUserNotFound",
  RoleUserAlreadyExist = "RoleUserAlreadyExist",
  RoleGroupNotFound = "RoleGroupNotFound",
  RoleGroupAlreadyExist = "RoleGroupAlreadyExist",
  InvalidSystemIdFormat = "InvalidSystemIdFormat",
  InvalidRoleIdFormat = "InvalidRoleIdFormat",
  InvalidUserIdFormat = "InvalidUserIdFormat",
  InvalidOwnerIdFormat = "InvalidOwnerIdFormat",
  InvalidGroupIdFormat = "InvalidGroupIdorPostFormat",
  InvalidNameOrPassword = "InvalidNameOrPassword",
  TokenNotFound = "TokenNotFound",
  InvalidToken = "InvalidToken",
  OwnerNotFound = "OwnerNotFound",
  PermissionDenied = "PermissionDenied",
  UserNotFound = "UserNotFound",
  InvalidIdOrPassword = "InvalidIdOrPassword",
  InvalidFormat = "InvalidFormat",
  MaintainerAlreadyExist = "MaintainerAlreadyExist",
  MaintainerNotFound = "MaintainerNotFound"
}
export default ErrorKind;
